/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cadastrar/': RouteRecordInfo<
      '/cadastrar/',
      '/cadastrar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/esqueci-senha/': RouteRecordInfo<
      '/esqueci-senha/',
      '/esqueci-senha',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login-codigo/': RouteRecordInfo<
      '/login-codigo/',
      '/login-codigo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login-magico/': RouteRecordInfo<
      '/login-magico/',
      '/login-magico',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/logout/': RouteRecordInfo<
      '/logout/',
      '/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/verificar-email/': RouteRecordInfo<
      '/verificar-email/',
      '/verificar-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/cadastrar/index.vue': {
      routes:
        | '/cadastrar/'
      views:
        | never
    }
    'src/pages/esqueci-senha/index.vue': {
      routes:
        | '/esqueci-senha/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/login-codigo/index.vue': {
      routes:
        | '/login-codigo/'
      views:
        | never
    }
    'src/pages/login-magico/index.vue': {
      routes:
        | '/login-magico/'
      views:
        | never
    }
    'src/pages/logout/index.vue': {
      routes:
        | '/logout/'
      views:
        | never
    }
    'src/pages/verificar-email/index.vue': {
      routes:
        | '/verificar-email/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
